### ISSUE TITLE
[Blackout] Shader is not Single-pass instanced compatiable

### ISSUE THREAD

**Issue by Nirv-git** [NotAKidOnSteam/NAK_CVR_Mods#26]
The shader used for the blackout effect is not Single-pass instanced compatible and only renders in the left eye when in VR

**Comment by NotAKidOnSteam** [comment]
It's on my todo list but I lost the shader and forgot how to make bundles. Just haven't had time to go fix it.

**Comment by NotAKidOnSteam** [comment]
mod is now maintained by Nirv-git https://github.com/Nirv-git/NAK_CVR_Mods/tree/main/Blackout

Feel free to fork/merge that into your own repo btw.
